packages:
  - "app/*"
  - "packages/*"
  - "services/*"
minimumReleaseAge: 0
allowBuilds:
  "@prisma/engines": true
  esbuild: true
  msgpackr-extract: false
  prisma: true
  sharp: true
  unrs-resolver: true
  workerd: false
