// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from "@prisma/orm-postgres/target/codec-types";
import type { QueryOperationTypes as PgTargetQueryOps } from "@prisma/orm-postgres/target/operation-types";

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from "@prisma/orm-postgres/family-contract/types";
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from "@prisma/orm-postgres/contract/types";

export type StorageHash =
  StorageHashBase<"f916aa31ca4b0033350dc3583937caf3a00d48fd7a116742955c2866322cca1d">;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<"3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2">;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8number@1";
      readonly nullable: false;
    };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
    readonly anyInput: {
      readonly output: "pg/int8@1";
      readonly nullable: false;
    };
  };
  readonly max: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly "pg/char@1": {
        readonly output: "pg/char@1";
        readonly nullable: true;
      };
      readonly "pg/date-string@1": {
        readonly output: "pg/date-string@1";
        readonly nullable: true;
      };
      readonly "pg/date-temporal@1": {
        readonly output: "pg/date-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/enum@1": {
        readonly output: "pg/enum@1";
        readonly nullable: true;
      };
      readonly "pg/float@1": {
        readonly output: "pg/float@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/inet@1": {
        readonly output: "pg/inet@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int2@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int4@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/text-array@1": {
        readonly output: "pg/text-array@1";
        readonly nullable: true;
      };
      readonly "pg/text@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/time-string@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/time-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-string@1": {
        readonly output: "pg/timestamp-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamp-temporal@1": {
        readonly output: "pg/timestamp-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-date@1": {
        readonly output: "pg/timestamptz-date@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-string@1": {
        readonly output: "pg/timestamptz-string@1";
        readonly nullable: true;
      };
      readonly "pg/timestamptz-temporal@1": {
        readonly output: "pg/timestamptz-temporal@1";
        readonly nullable: true;
      };
      readonly "pg/timetz@1": {
        readonly output: "pg/timetz@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
      readonly "sql/char@1": {
        readonly output: "sql/char@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "sql/float@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "sql/int@1";
        readonly nullable: true;
      };
      readonly "sql/text@1": {
        readonly output: "sql/text@1";
        readonly nullable: true;
      };
      readonly "sql/varchar@1": {
        readonly output: "pg/text@1";
        readonly nullable: true;
      };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly "pg/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/float4@1": {
        readonly output: "pg/float4@1";
        readonly nullable: true;
      };
      readonly "pg/float8@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "pg/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
      readonly "pg/interval@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/numeric@1": {
        readonly output: "pg/numeric@1";
        readonly nullable: true;
      };
      readonly "pg/time-string@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/time-temporal@1": {
        readonly output: "pg/interval@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/float@1": {
        readonly output: "pg/float8@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8number@1";
        readonly nullable: true;
      };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly "pg/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int2@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int4@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
      readonly "pg/int8@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/int8number@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "pg/unboundedint@1": {
        readonly output: "pg/unboundedint@1";
        readonly nullable: true;
      };
      readonly "sql/int@1": {
        readonly output: "pg/int8@1";
        readonly nullable: true;
      };
    };
  };
};
type DefaultLiteralValue<
  CodecId extends string,
  Encoded,
> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]["json"]
    ? Encoded
    : CodecTypes[CodecId]["json"]
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly MbtaPattern: {
      readonly directionId: CodecTypes["pg/int4@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly routeId: CodecTypes["pg/text@1"]["output"];
      readonly sortOrder: CodecTypes["pg/int4@1"]["output"];
      readonly typicality: CodecTypes["pg/int4@1"]["output"];
    };
    readonly MbtaPatternStop: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly patternId: CodecTypes["pg/text@1"]["output"];
      readonly position: CodecTypes["pg/int4@1"]["output"];
      readonly stopId: CodecTypes["pg/text@1"]["output"];
    };
    readonly MbtaRoute: {
      readonly attributes: CodecTypes["pg/jsonb@1"]["output"];
      readonly color: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly routeType: CodecTypes["pg/int4@1"]["output"];
      readonly sortOrder: CodecTypes["pg/int4@1"]["output"];
      readonly textColor: CodecTypes["pg/text@1"]["output"];
    };
    readonly MbtaStop: {
      readonly attributes: CodecTypes["pg/jsonb@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly latitude: CodecTypes["pg/float8@1"]["output"] | null;
      readonly locationType: CodecTypes["pg/int4@1"]["output"];
      readonly longitude: CodecTypes["pg/float8@1"]["output"] | null;
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly parentStationId: CodecTypes["pg/text@1"]["output"] | null;
    };
    readonly MbtaSyncState: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly lastAttemptAt: CodecTypes["pg/text@1"]["output"];
      readonly lastError: CodecTypes["pg/text@1"]["output"] | null;
      readonly lastSuccessAt: CodecTypes["pg/text@1"]["output"] | null;
      readonly patternCount: CodecTypes["pg/int4@1"]["output"];
      readonly routeCount: CodecTypes["pg/int4@1"]["output"];
      readonly stopCount: CodecTypes["pg/int4@1"]["output"];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly MbtaPattern: {
      readonly directionId: CodecTypes["pg/int4@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly routeId: CodecTypes["pg/text@1"]["input"];
      readonly sortOrder: CodecTypes["pg/int4@1"]["input"];
      readonly typicality: CodecTypes["pg/int4@1"]["input"];
    };
    readonly MbtaPatternStop: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly patternId: CodecTypes["pg/text@1"]["input"];
      readonly position: CodecTypes["pg/int4@1"]["input"];
      readonly stopId: CodecTypes["pg/text@1"]["input"];
    };
    readonly MbtaRoute: {
      readonly attributes: CodecTypes["pg/jsonb@1"]["input"];
      readonly color: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly routeType: CodecTypes["pg/int4@1"]["input"];
      readonly sortOrder: CodecTypes["pg/int4@1"]["input"];
      readonly textColor: CodecTypes["pg/text@1"]["input"];
    };
    readonly MbtaStop: {
      readonly attributes: CodecTypes["pg/jsonb@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly latitude: CodecTypes["pg/float8@1"]["input"] | null;
      readonly locationType: CodecTypes["pg/int4@1"]["input"];
      readonly longitude: CodecTypes["pg/float8@1"]["input"] | null;
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly parentStationId: CodecTypes["pg/text@1"]["input"] | null;
    };
    readonly MbtaSyncState: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly lastAttemptAt: CodecTypes["pg/text@1"]["input"];
      readonly lastError: CodecTypes["pg/text@1"]["input"] | null;
      readonly lastSuccessAt: CodecTypes["pg/text@1"]["input"] | null;
      readonly patternCount: CodecTypes["pg/int4@1"]["input"];
      readonly routeCount: CodecTypes["pg/int4@1"]["input"];
      readonly stopCount: CodecTypes["pg/int4@1"]["input"];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly MbtaPattern: {
      readonly directionId: CodecTypes["pg/int4@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly routeId: CodecTypes["pg/text@1"]["output"];
      readonly sortOrder: CodecTypes["pg/int4@1"]["output"];
      readonly typicality: CodecTypes["pg/int4@1"]["output"];
    };
    readonly MbtaPatternStop: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly patternId: CodecTypes["pg/text@1"]["output"];
      readonly position: CodecTypes["pg/int4@1"]["output"];
      readonly stopId: CodecTypes["pg/text@1"]["output"];
    };
    readonly MbtaRoute: {
      readonly attributes: CodecTypes["pg/jsonb@1"]["output"];
      readonly color: CodecTypes["pg/text@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly routeType: CodecTypes["pg/int4@1"]["output"];
      readonly sortOrder: CodecTypes["pg/int4@1"]["output"];
      readonly textColor: CodecTypes["pg/text@1"]["output"];
    };
    readonly MbtaStop: {
      readonly attributes: CodecTypes["pg/jsonb@1"]["output"];
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly latitude: CodecTypes["pg/float8@1"]["output"] | null;
      readonly locationType: CodecTypes["pg/int4@1"]["output"];
      readonly longitude: CodecTypes["pg/float8@1"]["output"] | null;
      readonly name: CodecTypes["pg/text@1"]["output"];
      readonly parentStationId: CodecTypes["pg/text@1"]["output"] | null;
    };
    readonly MbtaSyncState: {
      readonly id: CodecTypes["pg/text@1"]["output"];
      readonly lastAttemptAt: CodecTypes["pg/text@1"]["output"];
      readonly lastError: CodecTypes["pg/text@1"]["output"] | null;
      readonly lastSuccessAt: CodecTypes["pg/text@1"]["output"] | null;
      readonly patternCount: CodecTypes["pg/int4@1"]["output"];
      readonly routeCount: CodecTypes["pg/int4@1"]["output"];
      readonly stopCount: CodecTypes["pg/int4@1"]["output"];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly MbtaPattern: {
      readonly directionId: CodecTypes["pg/int4@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly routeId: CodecTypes["pg/text@1"]["input"];
      readonly sortOrder: CodecTypes["pg/int4@1"]["input"];
      readonly typicality: CodecTypes["pg/int4@1"]["input"];
    };
    readonly MbtaPatternStop: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly patternId: CodecTypes["pg/text@1"]["input"];
      readonly position: CodecTypes["pg/int4@1"]["input"];
      readonly stopId: CodecTypes["pg/text@1"]["input"];
    };
    readonly MbtaRoute: {
      readonly attributes: CodecTypes["pg/jsonb@1"]["input"];
      readonly color: CodecTypes["pg/text@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly routeType: CodecTypes["pg/int4@1"]["input"];
      readonly sortOrder: CodecTypes["pg/int4@1"]["input"];
      readonly textColor: CodecTypes["pg/text@1"]["input"];
    };
    readonly MbtaStop: {
      readonly attributes: CodecTypes["pg/jsonb@1"]["input"];
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly latitude: CodecTypes["pg/float8@1"]["input"] | null;
      readonly locationType: CodecTypes["pg/int4@1"]["input"];
      readonly longitude: CodecTypes["pg/float8@1"]["input"] | null;
      readonly name: CodecTypes["pg/text@1"]["input"];
      readonly parentStationId: CodecTypes["pg/text@1"]["input"] | null;
    };
    readonly MbtaSyncState: {
      readonly id: CodecTypes["pg/text@1"]["input"];
      readonly lastAttemptAt: CodecTypes["pg/text@1"]["input"];
      readonly lastError: CodecTypes["pg/text@1"]["input"] | null;
      readonly lastSuccessAt: CodecTypes["pg/text@1"]["input"] | null;
      readonly patternCount: CodecTypes["pg/int4@1"]["input"];
      readonly routeCount: CodecTypes["pg/int4@1"]["input"];
      readonly stopCount: CodecTypes["pg/int4@1"]["input"];
    };
  };
};

export namespace Models {
  export type public_MbtaPattern = {
    directionId: CodecTypes["pg/int4@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"];
    routeId: CodecTypes["pg/text@1"]["output"];
    sortOrder: CodecTypes["pg/int4@1"]["output"];
    typicality: CodecTypes["pg/int4@1"]["output"];
    route: public_MbtaRoute;
    stops: public_MbtaPatternStop[];
    readonly [RelationKeys]?: "route" | "stops";
  };
  export type public_MbtaPatternStop = {
    id: CodecTypes["pg/text@1"]["output"];
    patternId: CodecTypes["pg/text@1"]["output"];
    position: CodecTypes["pg/int4@1"]["output"];
    stopId: CodecTypes["pg/text@1"]["output"];
    pattern: public_MbtaPattern;
    stop: public_MbtaStop;
    readonly [RelationKeys]?: "pattern" | "stop";
  };
  export type public_MbtaRoute = {
    attributes: CodecTypes["pg/jsonb@1"]["output"];
    color: CodecTypes["pg/text@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    name: CodecTypes["pg/text@1"]["output"];
    routeType: CodecTypes["pg/int4@1"]["output"];
    sortOrder: CodecTypes["pg/int4@1"]["output"];
    textColor: CodecTypes["pg/text@1"]["output"];
    patterns: public_MbtaPattern[];
    readonly [RelationKeys]?: "patterns";
  };
  export type public_MbtaStop = {
    attributes: CodecTypes["pg/jsonb@1"]["output"];
    id: CodecTypes["pg/text@1"]["output"];
    latitude: CodecTypes["pg/float8@1"]["output"] | null;
    locationType: CodecTypes["pg/int4@1"]["output"];
    longitude: CodecTypes["pg/float8@1"]["output"] | null;
    name: CodecTypes["pg/text@1"]["output"];
    parentStationId: CodecTypes["pg/text@1"]["output"] | null;
    patternStops: public_MbtaPatternStop[];
    readonly [RelationKeys]?: "patternStops";
  };
  export type public_MbtaSyncState = {
    id: CodecTypes["pg/text@1"]["output"];
    lastAttemptAt: CodecTypes["pg/text@1"]["output"];
    lastError: CodecTypes["pg/text@1"]["output"] | null;
    lastSuccessAt: CodecTypes["pg/text@1"]["output"] | null;
    patternCount: CodecTypes["pg/int4@1"]["output"];
    routeCount: CodecTypes["pg/int4@1"]["output"];
    stopCount: CodecTypes["pg/int4@1"]["output"];
    readonly [RelationKeys]?: never;
  };
}

export declare const models: {
  public: {
    MbtaPattern: Models.public_MbtaPattern;
    MbtaPatternStop: Models.public_MbtaPatternStop;
    MbtaRoute: Models.public_MbtaRoute;
    MbtaStop: Models.public_MbtaStop;
    MbtaSyncState: Models.public_MbtaSyncState;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: "public";
        readonly kind: "postgres-schema";
        readonly entries: {
          readonly table: {
            readonly MbtaPattern: {
              columns: {
                readonly directionId: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly routeId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly sortOrder: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly typicality: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "MbtaPattern_routeId_idx_91ae2fd6";
                  readonly prefix: "MbtaPattern_routeId_idx";
                  readonly columns: readonly ["routeId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "MbtaPattern";
                    readonly columns: readonly ["routeId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "MbtaRoute";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly MbtaPatternStop: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly patternId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly position: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly stopId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "MbtaPatternStop_patternId_idx_31993061";
                  readonly prefix: "MbtaPatternStop_patternId_idx";
                  readonly columns: readonly ["patternId"];
                  readonly unique: false;
                },
                {
                  readonly name: "MbtaPatternStop_patternId_position_idx_f5b2ee9d";
                  readonly prefix: "MbtaPatternStop_patternId_position_idx";
                  readonly columns: readonly ["patternId", "position"];
                  readonly unique: true;
                },
                {
                  readonly name: "MbtaPatternStop_stopId_idx_8804d4e7";
                  readonly prefix: "MbtaPatternStop_stopId_idx";
                  readonly columns: readonly ["stopId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "MbtaPatternStop";
                    readonly columns: readonly ["patternId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "MbtaPattern";
                    readonly columns: readonly ["id"];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "MbtaPatternStop";
                    readonly columns: readonly ["stopId"];
                  };
                  readonly target: {
                    readonly namespaceId: "public" & NamespaceId;
                    readonly tableName: "MbtaStop";
                    readonly columns: readonly ["id"];
                  };
                },
              ];
            };
            readonly MbtaRoute: {
              columns: {
                readonly attributes: {
                  readonly nativeType: "jsonb";
                  readonly codecId: "pg/jsonb@1";
                  readonly nullable: false;
                };
                readonly color: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly routeType: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly sortOrder: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly textColor: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly MbtaStop: {
              columns: {
                readonly attributes: {
                  readonly nativeType: "jsonb";
                  readonly codecId: "pg/jsonb@1";
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly latitude: {
                  readonly nativeType: "float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: true;
                };
                readonly locationType: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly longitude: {
                  readonly nativeType: "float8";
                  readonly codecId: "pg/float8@1";
                  readonly nullable: true;
                };
                readonly name: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly parentStationId: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: "MbtaStop_parentStationId_idx_8eb11c00";
                  readonly prefix: "MbtaStop_parentStationId_idx";
                  readonly columns: readonly ["parentStationId"];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly MbtaSyncState: {
              columns: {
                readonly id: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly lastAttemptAt: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: false;
                };
                readonly lastError: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly lastSuccessAt: {
                  readonly nativeType: "text";
                  readonly codecId: "pg/text@1";
                  readonly nullable: true;
                };
                readonly patternCount: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly routeCount: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
                readonly stopCount: {
                  readonly nativeType: "int4";
                  readonly codecId: "pg/int4@1";
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ["id"] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  "roots" | "domain"
> & {
  readonly target: "postgres";
  readonly targetFamily: "sql";
  readonly roots: {
    readonly MbtaPattern: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "MbtaPattern";
    };
    readonly MbtaPatternStop: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "MbtaPatternStop";
    };
    readonly MbtaRoute: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "MbtaRoute";
    };
    readonly MbtaStop: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "MbtaStop";
    };
    readonly MbtaSyncState: {
      readonly namespace: "public" & NamespaceId;
      readonly model: "MbtaSyncState";
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly MbtaPattern: {
            readonly fields: {
              readonly directionId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly routeId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly typicality: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
            };
            readonly relations: {
              readonly route: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "MbtaRoute";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["routeId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly stops: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "MbtaPatternStop";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["patternId"];
                };
              };
            };
            readonly storage: {
              readonly table: "MbtaPattern";
              readonly namespaceId: "public";
              readonly fields: {
                readonly directionId: { readonly column: "directionId" };
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly routeId: { readonly column: "routeId" };
                readonly sortOrder: { readonly column: "sortOrder" };
                readonly typicality: { readonly column: "typicality" };
              };
            };
          };
          readonly MbtaPatternStop: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly patternId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly position: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly stopId: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
            };
            readonly relations: {
              readonly pattern: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "MbtaPattern";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["patternId"];
                  readonly targetFields: readonly ["id"];
                };
              };
              readonly stop: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "MbtaStop";
                };
                readonly cardinality: "N:1";
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ["stopId"];
                  readonly targetFields: readonly ["id"];
                };
              };
            };
            readonly storage: {
              readonly table: "MbtaPatternStop";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly patternId: { readonly column: "patternId" };
                readonly position: { readonly column: "position" };
                readonly stopId: { readonly column: "stopId" };
              };
            };
          };
          readonly MbtaRoute: {
            readonly fields: {
              readonly attributes: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/jsonb@1";
                };
              };
              readonly color: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly routeType: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly sortOrder: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly textColor: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
            };
            readonly relations: {
              readonly patterns: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "MbtaPattern";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["routeId"];
                };
              };
            };
            readonly storage: {
              readonly table: "MbtaRoute";
              readonly namespaceId: "public";
              readonly fields: {
                readonly attributes: { readonly column: "attributes" };
                readonly color: { readonly column: "color" };
                readonly id: { readonly column: "id" };
                readonly name: { readonly column: "name" };
                readonly routeType: { readonly column: "routeType" };
                readonly sortOrder: { readonly column: "sortOrder" };
                readonly textColor: { readonly column: "textColor" };
              };
            };
          };
          readonly MbtaStop: {
            readonly fields: {
              readonly attributes: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/jsonb@1";
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly latitude: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/float8@1";
                };
              };
              readonly locationType: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly longitude: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/float8@1";
                };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly parentStationId: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
            };
            readonly relations: {
              readonly patternStops: {
                readonly to: {
                  readonly namespace: "public" & NamespaceId;
                  readonly model: "MbtaPatternStop";
                };
                readonly cardinality: "1:N";
                readonly on: {
                  readonly localFields: readonly ["id"];
                  readonly targetFields: readonly ["stopId"];
                };
              };
            };
            readonly storage: {
              readonly table: "MbtaStop";
              readonly namespaceId: "public";
              readonly fields: {
                readonly attributes: { readonly column: "attributes" };
                readonly id: { readonly column: "id" };
                readonly latitude: { readonly column: "latitude" };
                readonly locationType: { readonly column: "locationType" };
                readonly longitude: { readonly column: "longitude" };
                readonly name: { readonly column: "name" };
                readonly parentStationId: {
                  readonly column: "parentStationId";
                };
              };
            };
          };
          readonly MbtaSyncState: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly lastAttemptAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly lastError: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly lastSuccessAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/text@1";
                };
              };
              readonly patternCount: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly routeCount: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
              readonly stopCount: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: "scalar";
                  readonly codecId: "pg/int4@1";
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: "MbtaSyncState";
              readonly namespaceId: "public";
              readonly fields: {
                readonly id: { readonly column: "id" };
                readonly lastAttemptAt: { readonly column: "lastAttemptAt" };
                readonly lastError: { readonly column: "lastError" };
                readonly lastSuccessAt: { readonly column: "lastSuccessAt" };
                readonly patternCount: { readonly column: "patternCount" };
                readonly routeCount: { readonly column: "routeCount" };
                readonly stopCount: { readonly column: "stopCount" };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract["storage"]["namespaces"];
