// lib/buildSendWeatherEmail.ts
import { db } from "@/lib/db";

const API_KEY = process.env.TOMORROWIO_APIKEY!;

async function fetchWeatherForCity(city: string) {
  const url = `https://api.tomorrow.io/v4/weather/realtime?location=${encodeURIComponent(
    city,
  )}&units=imperial&apikey=${API_KEY}`;

  const res = await fetch(url);
  if (!res.ok) return null;

  const json = await res.json();
  const v = json?.data?.values;

  if (!v) return null;

  return {
    temperature: v.temperature,
    feelsLike: v.temperatureApparent,
    humidity: v.humidity,
    windSpeed: v.windSpeed,
    visibility: v.visibility,
    weatherCode: v.weatherCode,
    fetchedAt: new Date(),
  };
}

export async function buildSendWeatherEmail() {
  // 1. Get the most recent snapshot
  const snapshot = await db.travelSnapshot.findFirst({
    orderBy: { receivedAt: "desc" },
    include: { segments: true },
  });

  if (!snapshot) {
    return {
      subject: "Your Upcoming Trip",
      text: "No upcoming trip found.",
      html: `<p>No upcoming trip found.</p>`,
    };
  }

  const segments = snapshot.segments.sort((a, b) =>
    a.departureTime.localeCompare(b.departureTime),
  );

  if (segments.length === 0) {
    return {
      subject: "Your Upcoming Trip",
      text: "No segments found for this trip.",
      html: `<p>No segments found for this trip.</p>`,
    };
  }

  // 2. Fetch weather for each arrival city
  const weatherByCity: Record<string, any> = {};

  for (const seg of segments) {
    weatherByCity[seg.arrivalCity] = await fetchWeatherForCity(seg.arrivalCity);
  }

  const [outbound, inbound] = segments;

  const outWeather = weatherByCity[outbound.arrivalCity];
  const inWeather = weatherByCity[inbound.arrivalCity];

  const formatTemp = (t: number | null | undefined) =>
    t != null ? `${t}°F` : "—";

  // 3. Build HTML
  const html = `
  <div style="font-family: system-ui, sans-serif; padding: 20px; color: #0a2540;">
    <h1 style="margin-bottom: 10px;">Your Upcoming Trip</h1>

    <p style="color: #555; margin-top: 0;">
      Automatically generated by your Travel Dashboard
    </p>

    <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;" />

    <!-- OUTBOUND -->
    <h2 style="margin-bottom: 5px;">Outbound Flight</h2>
    <p style="margin: 0 0 10px 0;">
      <strong>${outbound.departureCity} → ${outbound.arrivalCity}</strong><br/>
      ${outbound.date}<br/>
      ${outbound.departureTime} → ${outbound.arrivalTime}<br/>
      Seats: ${outbound.seats.join(", ")}
    </p>

    <h3 style="margin: 10px 0 5px;">Weather on Arrival</h3>
    ${
      outWeather
        ? `
        <div style="padding: 10px; background: #f0f7ff; border-radius: 8px;">
          <div><strong>Temperature:</strong> ${formatTemp(outWeather.temperature)}</div>
          <div><strong>Feels Like:</strong> ${formatTemp(outWeather.feelsLike)}</div>
          <div><strong>Humidity:</strong> ${outWeather.humidity ?? "—"}%</div>
          <div><strong>Wind:</strong> ${outWeather.windSpeed ?? "—"} mph</div>
          <div><strong>Visibility:</strong> ${outWeather.visibility ?? "—"} mi</div>
          <div style="font-size: 12px; color: #666; margin-top: 5px;">
            Updated: ${outWeather.fetchedAt.toLocaleString()}
          </div>
        </div>
      `
        : `<p>No weather data available.</p>`
    }

    <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;" />

    <!-- RETURN -->
    <h2 style="margin-bottom: 5px;">Return Flight</h2>
    <p style="margin: 0 0 10px 0;">
      <strong>${inbound.departureCity} → ${inbound.arrivalCity}</strong><br/>
      ${inbound.date}<br/>
      ${inbound.departureTime} → ${inbound.arrivalTime}<br/>
      Seats: ${inbound.seats.join(", ")}
    </p>

    <h3 style="margin: 10px 0 5px;">Weather on Return</h3>
    ${
      inWeather
        ? `
        <div style="padding: 10px; background: #f0f7ff; border-radius: 8px;">
          <div><strong>Temperature:</strong> ${formatTemp(inWeather.temperature)}</div>
          <div><strong>Feels Like:</strong> ${formatTemp(inWeather.feelsLike)}</div>
          <div><strong>Humidity:</strong> ${inWeather.humidity ?? "—"}%</div>
          <div><strong>Wind:</strong> ${inWeather.windSpeed ?? "—"} mph</div>
          <div><strong>Visibility:</strong> ${inWeather.visibility ?? "—"} mi</div>
          <div style="font-size: 12px; color: #666; margin-top: 5px;">
            Updated: ${inWeather.fetchedAt.toLocaleString()}
          </div>
        </div>
      `
        : `<p>No weather data available.</p>`
    }

    <hr style="margin: 20px 0; border: none; border-top: 1px solid #ddd;" />

    <p style="font-size: 12px; color: #666;">
      Travel Weather Bot • ${new Date().toLocaleString()}
    </p>
  </div>
  `;

  return {
    subject: `Your Upcoming Trip: ${outbound.departureCity} → ${outbound.arrivalCity}`,
    text: `Your upcoming trip details are ready.`,
    html,
  };
}
